python -u run.py --is_training 1 --root_path ./target_data --data_path data_test_4.csv --model_id test --model iTransformer --data custom --features MS --target WaterTemperature --seq_len 4384 --label_len 4384 --pred_len 24 --e_layers 3 --enc_in 7 --dec_in 7 --c_out 1 --des '6 Months History' --d_model 512 --d_ff 512 --itr 1 --train_epochs 10 --do_predict --inverse > ./logs/6month_log.txt 2>&1

python -u run.py --is_training 1 --root_path ./target_data --data_path data_test_4.csv --model_id test --model iTransformer --data custom --features MS --target WaterTemperature --seq_len 8767 --label_len 8767 --pred_len 24 --e_layers 3 --enc_in 7 --dec_in 7 --c_out 1 --des '12 Months History' --d_model 512 --d_ff 512 --itr 1 --train_epochs 10 --do_predict --inverse > ./logs/12month_log.txt 2>&1

python -u run.py --is_training 1 --root_path ./target_data --data_path data_test_4.csv --model_id test --model iTransformer --data custom --features MS --target WaterTemperature --seq_len 13150 --label_len 13150 --pred_len 24 --e_layers 3 --enc_in 7 --dec_in 7 --c_out 1 --des '18 Months History' --d_model 512 --d_ff 512 --itr 1 --train_epochs 10 --do_predict --inverse > ./logs/18month_log.txt 2>&1

python -u run.py --is_training 1 --root_path ./target_data --data_path data_test_4.csv --model_id test --model iTransformer --data custom --features MS --target WaterTemperature --seq_len 17534 --label_len 17534 --pred_len 24 --e_layers 3 --enc_in 7 --dec_in 7 --c_out 1 --des '24 Months History' --d_model 512 --d_ff 512 --itr 1 --train_epochs 10 --do_predict --inverse > ./logs/24month_log.txt 2>&1

python -u run.py --is_training 1 --root_path ./target_data --data_path data_test_4.csv --model_id test --model iTransformer --data custom --features MS --target WaterTemperature --seq_len 21917 --label_len 21917 --pred_len 24 --e_layers 3 --enc_in 7 --dec_in 7 --c_out 1 --des '30 Months History' --d_model 512 --d_ff 512 --itr 1 --train_epochs 10 --do_predict --inverse > ./logs/30month_log.txt 2>&1
