#python -u run.py --is_training 1 --root_path ./target_data/specific_month --data_path 1_mr_month_1_data.csv --model_id test --model iTransformer --data custom --features MS --target WaterTemperature --seq_len 731 --label_len 731 --pred_len 24 --e_layers 3 --enc_in 7 --dec_in 7 --c_out 1 --des 'January 1 Year Range' --d_model 512 --d_ff 512 --itr 1 --train_epochs 10 --do_predict --inverse > ./logs/specific_month/1_mr_month_1.txt 2>&1

python -u run.py --is_training 1 --root_path ./target_data/specific_month --data_path 1_mr_month_2_data.csv --model_id test --model iTransformer --data custom --features MS --target WaterTemperature --seq_len 731 --label_len 731 --pred_len 24 --e_layers 3 --enc_in 7 --dec_in 7 --c_out 1 --des 'February 1 Year Range' --d_model 512 --d_ff 512 --itr 1 --train_epochs 10 --do_predict --inverse > ./logs/specific_month/1_mr_month_2.txt 2>&1

python -u run.py --is_training 1 --root_path ./target_data/specific_month --data_path 1_mr_month_3_data.csv --model_id test --model iTransformer --data custom --features MS --target WaterTemperature --seq_len 731 --label_len 731 --pred_len 24 --e_layers 3 --enc_in 7 --dec_in 7 --c_out 1 --des 'March 1 Year Range' --d_model 512 --d_ff 512 --itr 1 --train_epochs 10 --do_predict --inverse > ./logs/specific_month/1_mr_month_3.txt 2>&1

python -u run.py --is_training 1 --root_path ./target_data/specific_month --data_path 1_mr_month_4_data.csv --model_id test --model iTransformer --data custom --features MS --target WaterTemperature --seq_len 731 --label_len 731 --pred_len 24 --e_layers 3 --enc_in 7 --dec_in 7 --c_out 1 --des 'April 1 Year Range' --d_model 512 --d_ff 512 --itr 1 --train_epochs 10 --do_predict --inverse > ./logs/specific_month/1_mr_month_4.txt 2>&1

python -u run.py --is_training 1 --root_path ./target_data/specific_month --data_path 1_mr_month_5_data.csv --model_id test --model iTransformer --data custom --features MS --target WaterTemperature --seq_len 731 --label_len 731 --pred_len 24 --e_layers 3 --enc_in 7 --dec_in 7 --c_out 1 --des 'May 1 Year Range' --d_model 512 --d_ff 512 --itr 1 --train_epochs 10 --do_predict --inverse > ./logs/specific_month/1_mr_month_5.txt 2>&1

python -u run.py --is_training 1 --root_path ./target_data/specific_month --data_path 1_mr_month_6_data.csv --model_id test --model iTransformer --data custom --features MS --target WaterTemperature --seq_len 731 --label_len 731 --pred_len 24 --e_layers 3 --enc_in 7 --dec_in 7 --c_out 1 --des 'June 1 Year Range' --d_model 512 --d_ff 512 --itr 1 --train_epochs 10 --do_predict --inverse > ./logs/specific_month/1_mr_month_6.txt 2>&1

python -u run.py --is_training 1 --root_path ./target_data/specific_month --data_path 1_mr_month_7_data.csv --model_id test --model iTransformer --data custom --features MS --target WaterTemperature --seq_len 731 --label_len 731 --pred_len 24 --e_layers 3 --enc_in 7 --dec_in 7 --c_out 1 --des 'July 1 Year Range' --d_model 512 --d_ff 512 --itr 1 --train_epochs 10 --do_predict --inverse > ./logs/specific_month/1_mr_month_7.txt 2>&1

python -u run.py --is_training 1 --root_path ./target_data/specific_month --data_path 1_mr_month_8_data.csv --model_id test --model iTransformer --data custom --features MS --target WaterTemperature --seq_len 731 --label_len 731 --pred_len 24 --e_layers 3 --enc_in 7 --dec_in 7 --c_out 1 --des 'August 1 Year Range' --d_model 512 --d_ff 512 --itr 1 --train_epochs 10 --do_predict --inverse > ./logs/specific_month/1_mr_month_8.txt 2>&1

python -u run.py --is_training 1 --root_path ./target_data/specific_month --data_path 1_mr_month_9_data.csv --model_id test --model iTransformer --data custom --features MS --target WaterTemperature --seq_len 731 --label_len 731 --pred_len 24 --e_layers 3 --enc_in 7 --dec_in 7 --c_out 1 --des 'September 1 Year Range' --d_model 512 --d_ff 512 --itr 1 --train_epochs 10 --do_predict --inverse > ./logs/specific_month/1_mr_month_9.txt 2>&1

python -u run.py --is_training 1 --root_path ./target_data/specific_month --data_path 1_mr_month_10_data.csv --model_id test --model iTransformer --data custom --features MS --target WaterTemperature --seq_len 731 --label_len 731 --pred_len 24 --e_layers 3 --enc_in 7 --dec_in 7 --c_out 1 --des 'October 1 Year Range' --d_model 512 --d_ff 512 --itr 1 --train_epochs 10 --do_predict --inverse > ./logs/specific_month/1_mr_month_10.txt 2>&1

python -u run.py --is_training 1 --root_path ./target_data/specific_month --data_path 1_mr_month_11_data.csv --model_id test --model iTransformer --data custom --features MS --target WaterTemperature --seq_len 731 --label_len 731 --pred_len 24 --e_layers 3 --enc_in 7 --dec_in 7 --c_out 1 --des 'November 1 Year Range' --d_model 512 --d_ff 512 --itr 1 --train_epochs 10 --do_predict --inverse > ./logs/specific_month/1_mr_month_11.txt 2>&1

python -u run.py --is_training 1 --root_path ./target_data/specific_month --data_path 1_mr_month_12_data.csv --model_id test --model iTransformer --data custom --features MS --target WaterTemperature --seq_len 731 --label_len 731 --pred_len 24 --e_layers 3 --enc_in 7 --dec_in 7 --c_out 1 --des 'December 1 Year Range' --d_model 512 --d_ff 512 --itr 1 --train_epochs 10 --do_predict --inverse > ./logs/specific_month/1_mr_month_12.txt 2>&1